name: build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Check format
        run: npm run check-format
      - name: Run linter
        run: npm run lint
      - run: mkdir bin
      - name: Build
        run: npm run package
