name: dev_build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Install GUI dependencies
        run: npm install
      - name: Install Service dependencies
        working-directory: anonymizer
        run: dotnet tool restore
      - name: Check TS files format
        run: npm run check-format
      - name: Check F# files format
        working-directory: anonymizer
        run: dotnet fantomas --check OpenDiffix.Service
      - name: Run TS linter
        run: npm run lint
      - name: Build Service
        run: npm run build
      - name: Build App
        run: npm run package
